### ISSUE TITLE
Using psp-gdb with usbhostfs_pc is not documented on github pages site

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psplinkusb#22]
Well, it is documented in the PDF, but not on the github pages site, which should be changed.

**Comment by sharkwouter** [comment]
I'm going to assign this to me, so I don't lose track of it, but anyone can pick it up and implement it since I won't start on it right now.

**Comment by diamant3** [comment]
Hello @sharkwouter, I want to take this but do I need to setup the psplinkusb before documenting?

**Comment by sharkwouter** [comment]
That's cool @diamant3, thanks! I would say setting it up makes it easier, but you can probably get by with this document as well: https://github.com/pspdev/psplinkusb/blob/master/psplink_manual.pdf

A short summary of the process:
- Build your program with the BUILD_PRX option set and debug symbols enabled (build type Debug in cmake).
- Start psplink on the psp and connect it through usb
- Run usbhostfs_pc in the directory the prx is located and keep this running.
-  Run pspsh and use the debug command on the prx
- Now run psp-gdb on the elf file, not the prx.
- I think the command you need to connect is: target remote :10001
- Now you can set breakpoints, start the program, step through, get a stack trace if a crash happens, etc. I don't know the exact commands. I think c is for starting s is for stepping b is breakpoint bt is stacktrace, You can find documentation on it I'm sure. I think run doesn't work.

Hope that helps. That's just off the top of my head. Make sure to verify it with actual documentation.

**Comment by diamant3** [comment]
Got it! Thanks for the summary, that would be a big help. I'll work on it now

**Comment by sajattack** [comment]
I use gdb a fair bit. Please ping me when this is ready for review.

**Comment by diamant3** [comment]
Hello @sajattack my PR#34 is ready for review, thanks!
