### ISSUE TITLE
cygncursesw-10.dll missing

### ISSUE THREAD

**Issue by Fewnity** [pspdev/psplinkusb#38]
When I try to start pspsh.exe or usbhostfs_pc.exe I have an error saying "cygncursesw-10.dll" is missing, someone knows why?

**Comment by sajattack** [comment]
Install cygwin

**Comment by sharkwouter** [comment]
That's odd, which release did you download? I'm looking at the pspsh-windows.zip from the 3.1.1 release and it seems the dll you mention is included.

**Comment by Fewnity** [comment]
> That's odd, which release did you download? I'm looking at the pspsh-windows.zip from the 3.1.1 release and it seems the dll you mention is included.

I downloaded the Development build of last week
https://github.com/pspdev/psplinkusb/releases/download/latest/pspsh-windows.zip

**Comment by sharkwouter** [comment]
This is caused by #33, but I still need to investigate why this issue is happening.

**Comment by sharkwouter** [comment]
It turns out libreadline depends on ncurses, so we need it to be added back. I'll reverse the changes from #33

**Comment by sharkwouter** [comment]
This should be fixed now. Sorry it took a while, this issue was quite confusing.
