### ISSUE TITLE
PSPSH doesn't actually register verbose flag

### ISSUE THREAD

**Issue by playday3008** [pspdev/psplinkusb#55]
https://github.com/pspdev/psplinkusb/blob/00cd43b0ee41b5a037346616453abc7dffbb48d5/pspsh/pspsh.cpp#L1083

**Comment by sharkwouter** [comment]
Thanks for the report. That looks like an easy to fix oversight.

**Comment by sharkwouter** [comment]
I made a PR which solves this. Thanks again!
